# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=200)),
                ('masv', models.CharField(max_length=200)),
                ('nganhhoc', models.CharField(max_length=100)),
            ],
        ),
    ]
